
# Loads default set of integrations. Do not remove.
default_config:

debugpy:
  start: true
  #wait: true
  wait: false
  #host: 127.0.0.1
  host: 172.17.0.2
  port: 6712

# Text to speech
# tts:
#   - platform: google_translate

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml


# Example configuration.yaml entry

# custom_sensor_1:

sensor:
  - platform: custom_sensor_1
#  - platform: example_sensor

# Example configuration.yaml entry
logger:
  default: fatal
  logs:
    # log level for HA core
    homeassistant.core: fatal

    # log level for MQTT integration
    homeassistant.components.mqtt: fatal

    # log level for the `aiohttp` Python package
    aiohttp: error

    # log level for both 'glances_api' and 'glances' integration
    homeassistant.components.glances: fatal
    glances_api: fatal

    homeassistant.loader: fatal

    # log level for all python scripts
    homeassistant.components.python_script: fatal

    # individual log level for this python script
    # homeassistant.components.python_script.my_new_script.py: debug

    # log level for a custom component
    custom_components.custom_sensor_1: fatal
    custom_components.custom_sensor_1.my_api: fatal
    custom_components.custom_sensor_1.sensor: fatal
    custom_components.custom_sensor_1.sensor.MyCoordinator: fatal
    custom_components.custom_sensor_1.sensor.CoordinatedExampleSensor: fatal
    custom_components.custom_sensor_1.sensor.experimental: debug
    custom_components.custom_sensor_1.sensor.debug_domains: fatal
    custom_components.custom_sensor_1.sensor.debug_entities_all: fatal
    custom_components.custom_sensor_1.sensor.debug_entity_ids: fatal
