
# Loads default set of integrations.
# default_config:

application_credentials:
automation:
#bluetooth:
#cloud:
counter:
dhcp:
#energy:
frontend:
hardware:
history:
homeassistant_alerts:
input_boolean:
input_button:
input_datetime:
input_number:
input_select:
input_text:
logbook:
#map:
media_source:
mobile_app:
my:
network:
person:
scene:
schedule:
script:
#ssdp:
sun:
system_health:
tag:
timer:
#usb:
webhook:
#zeroconf:
zone:



debugpy:
  start: true
  #wait: true
  wait: false
  host: 172.17.0.2
  port: 6712

# Text to speech
# tts:
#   - platform: google_translate

# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml


# Example configuration.yaml entry

# sensor:
#   - platform: custom_sensor_1


#  - platform: example_sensor

# Example configuration.yaml entry
logger:
# critical
# fatal
# error
# warning
# warn
# info
# debug
# notset
  default: info
  logs:
    homeassistant.core: info
    homeassistant.loader: warning
    homeassistant.bootstrap: warning
    homeassistant.helpers: info
    homeassistant.helpers.entity_registry: info

    homeassistant.setup: warning

    asyncio: error
    aiohttp: error
    glances_api: error
    matplotlib.font_manager: error
    homeassistant.components.websocket_api.http.connection: error
    homeassistant.components.recorder.util: error

    homeassistant.components.zeroconf: error
    homeassistant.components.glances: error
    homeassistant.components.scene: error
    homeassistant.components.notify: error
    homeassistant.components.mqtt: error
    homeassistant.components.python_script: error

    custom_components.custom_sensor_1: debug
    custom_components.custom_sensor_1.my_api: error
    custom_components.custom_sensor_1.sensor: error
    custom_components.custom_sensor_1.sensor.MyCoordinator: error
    custom_components.custom_sensor_1.sensor.CoordinatedExampleSensor: error
    custom_components.custom_sensor_1.sensor.experimental: debug
    custom_components.custom_sensor_1.sensor.debug_domains: error
    custom_components.custom_sensor_1.sensor.debug_entities_all: error
    custom_components.custom_sensor_1.sensor.debug_entity_ids: error
    custom_components.custom_sensor_1.config_flow: debug
    custom_components.custom_sensor_1.__init__: debug

